### ISSUE TITLE
Add support non-hard coded directories

### ISSUE THREAD

**Issue by Miles-Beck** [Smiley-McSmiles/jellyman#96]
I have a Jellyfin install on a Rasberry Pi 5 that is running Debian (Bookworm). Jellyman looks really nice and would be very helpful to backup my install but it does not support directories for my install.

Can you add support to allow pointing to the config and metadata directories.

My jellyfin config directory is located at: /etc/jellyfin
and the metdata directory is located at: /var/lib/jellyfin/metadata

**Comment by Smiley-McSmiles** [comment]
I'm sorry, but Jellyman is not something you add to an existing install. Since Jellyfin is such a complicated program with complicated directories. It can be very picky. And the backups scripts I have written do not support folders outside the /opt/jellyfin directory. It is possible for me to add this however, it's jut not the recommended way of doing things. And Jellyman strictly follows the recommended setup for compatibility. So if you would like to use Jellyman, you would need to either migrate or reinstall completely. Or you can install Jellyman/Jellyfin, and point the `/opt/jellyfin/jellyfin.sh` directories to where you have your config/cache/metadata directories.

**Comment by jpbaril** [comment]
This would also be very handy for Docker-installed Jellyfin.
